version: '3'
services:
  nginx:
    depends_on:
      - grpc_server
    container_name: nginx-with-grpc
    image: nginx:1.13.10
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/etc/nginx/logs

  fastapi:
    build:
      context: ./Fast_API
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/shared

  grpc_server:
    build:
      context: ./gRPC_server
    ports:
      - "50051:50051"
    volumes:
      - ./storage:/app/shared


  grpc_client:
    build:
      context: ./gRPC_Client
    environment:
      SERVER_URL: nginx:80





